name: scriptblox-discord-bot
services:
- name: bot
  source_dir: /
  github:
    repo: wjybgnia/Bypasser-Bot
    branch: main
  run_command: node src/index.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DISCORD_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: CLIENT_ID
    scope: RUN_TIME
    type: SECRET
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
